# Colors (BGR for OpenCV)
PLAYER_DEFAULT_COLOR = (0, 0, 255)
BALL_POSSESSION_COLOR = (0, 0, 255)
REFEREE_COLOR = (0, 255, 255)
BALL_COLOR = (0, 255, 0)
TEXT_COLOR = (0, 0, 0)

# Label Drawing
LABEL_RECTANGLE_WIDTH = 40
LABEL_RECTANGLE_HEIGHT = 20
LABEL_Y_OFFSET = 15
LABEL_X_TEXT_OFFSET = 12
LABEL_TEXT_SHIFT_THRESHOLD = 99

# Shape Properties
ELLIPSE_HEIGHT_RATIO = 0.35
ELLIPSE_START_ANGLE = -45
ELLIPSE_END_ANGLE = 235
ELLIPSE_THICKNESS = 2

TRIANGLE_SIZE = 10
TRIANGLE_Y_OFFSET = 20

# Font
FONT_SCALE = 0.6
FONT_THICKNESS = 2
